FROM yue9944882/swagger-gen

# Copy required files
COPY swagger-codegen/generate_client_in_container.sh /generate_client_in_container.sh
COPY preprocess_spec.py /
COPY custom_objects_spec.json /
COPY java-model-only.xml /generation_params.xml
COPY java-crd-model.sh /model.sh

ENTRYPOINT ["mvn-entrypoint.sh", "/model.sh"]
